version: "3.7"
services:

    server:
      image: wiotrek/fleet-back:issue32-2
      depends_on:
        - mysql
      volumes:
        - ./:/app/src
      ports:
        - "2137:80"
      networks:
          vpcbr:
              ipv4_address: 10.10.0.2

    front:
      image: wiotrek/fleet-web:stage5-82
      depends_on:
        - server
        - mysql
      volumes:
        - ./:/app/web
      ports:
        - "2138:4000"
      environment:
        - API_URL=https://fleet-api.norka.dev/api/
        
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
           - MYSQL_ROOT_PASSWORD=password
           - MYSQL_ROOT_HOST=%
        volumes:
           - ./data/mysql:/var/lib/mysql
           - ./db-init:/docker-entrypoint-initdb.d
        networks:
             vpcbr:
                 ipv4_address: 10.10.0.4

networks:
    vpcbr:
        driver: bridge
        ipam:
           config:
               - subnet: 10.10.0.0/16
